import { Inter} from 'next/font/google';
import './globals.css';

import { AppContextProvider } from '@/app/contexts/AppContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Sanrio',
  description: 'Generated by create next app',
  icons:{
    icon:['/favicon?v=4.ico'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']
  }

};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppContextProvider>
          {children}

        </AppContextProvider>
      </body>
    </html>
  );
}



