import localFont from "next/font/local"
import { Outfit, Modak} from 'next/font/google';
import './globals.css';
import Navbar from "@/app/components/Navbar/Navbar.js";

import { AppContextProvider } from '@/app/contexts/AppContext';




const outfit = Outfit({ subsets: ['latin'], variable: '--font-outfit' });
const modak = Modak({ subsets: ['latin'], weight: ['400'], variable: '--font-modak' });

export const metadata = {
  title: 'Sanrio',
  description: 'Generated by create next app',
  icons:{
    icon:['/favicon?v=4.ico'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']
  }

};


export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${outfit.variable}  ${modak.variable}`}>
        <AppContextProvider>
          <Navbar />
          {children}

        </AppContextProvider>
      </body>
    </html>
  );
}



